### ISSUE TITLE
compile_pytorch_model.py compile failures (model_path/constants.pkl not found)

### ISSUE THREAD

**Issue by ljkeller** [renesas-rz/rzv_drp-ai_tvm#22]
Hello,

I'm having compile failures with `compile_pytorch_model.py`. Heres my failure:
```bash
/drp-ai_tvm/tutorials# python3 compile_pytorch_model.py /home/models/spark_torch.pt -o spark_torch -s 1,3,28,28
[Check arguments]
  Input AI model         :  /home/models/spark_torch.pt
  SDK path               :  /opt/poky/3.1.21
  DRP-AI Translator path :  /opt/drp-ai_translator_release
  Output dir             :  spark_torch
  Input shape            :  (1, 3, 28, 28)
Traceback (most recent call last):
  File "compile_pytorch_model.py", line 69, in <module>
    model = torch.jit.load(model_file)
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_serialization.py", line 161, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: [enforce fail at inline_container.cc:222] . file not found: v1.0.1_9_epochs_no_norm_97.27/constants.pkl
```

Interestingly, I trained this model and deployed to both torch and onnx formats. The onnx export works `python3 compile_onnx_model.py /home/models/spark.onnx -o spark -s 1,3,28,28 -i input`.

I'm guessing there is a version incompatibility with the torch I trained/exported on and the torch used here for the conversion? I don't see any documentation about expected torch training versions. I don't have my model training PC with me right now, or I'd report the torch version.

Here are the models I've tried [spark.zip](https://github.com/user-attachments/files/15570692/spark.zip)

## Environment

I'm running out of a docker container I built ~6 months ago with `docker build -t rzv2l_ai_sdk_image --build-arg SDK="/opt/poky/3.1.21" --build-arg PRODUCT="V2L" ` as far as I know.

**Comment by matinlotfali** [comment]
@ljkeller I have the exact same issue. Were you able to fix it?

**Comment by ljkeller** [comment]
> @ljkeller I have the exact same issue. Were you able to fix it?

I believe I put a PR out to fix this? https://github.com/renesas-rz/rzv_drp-ai_tvm/pull/23

Otherwise, this was a versioning issue. I can check my notes in the morning when I’m out of bed.

@matinlotfali please let me know if you get around the issue.

**Comment by matinlotfali** [comment]
I just learned that the PyTorch model file should be converted to a TorchScripted model via `torch.jit.trace` to work.

**Comment by ljkeller** [comment]
> I just learned that the PyTorch model file should be converted to a TorchScripted model via `torch.jit.trace` to work.

I've definitely compiled torch models without doing this explicitly. Do you have a link so I can read up on this?

**Comment by matinlotfali** [comment]
I think this is a nice reading material: https://www.geeksforgeeks.org/what-are-torch-scripts-in-pytorch/

**Comment by ljkeller** [comment]
Yes, but I was looking for an explicit callout of the necessity of the jit. Even the TVM docs don't appear to say much from what I've seen.

> We grab the TorchScripted model via tracing

 is all their [torch compile guide says.](https://tvm.apache.org/docs/how_to/compile_models/from_pytorch.html).

I think this is a recipe for wasted developer time. I could add a failure log warning to _tutorials/compile_pytorch_model*.py_ files on the jit.load if anyone thinks that would be useful? That or some documentation could be updated- I'm not sure where.

**Comment by hiroyuki-sakamoto** [comment]
Sorry for the delay in responding due to the confusion that accompanied the v2.4.0 release.
I have been looking at this issue 22 and feel it is necessary to add a note that the TorchScript model is required. Also, for various reasons, we are not accustomed to receiving contributions and incorporating them into the Quick, but we appreciate your offer. The next update is scheduled for the end of this year, when we hope to include documentation improvements, etc.

**Comment by hiroyuki-sakamoto** [comment]
Thanks for the discussion. As noted, the input `.pt` must be a **TorchScript** model.

We added a note about this since **v2.5.0** (2025-03), under "2. Compile PyTorch models" in `tutorials/README.md` (and `tutorials/tutorial_RZV2H.md` for RZ/V2H and RZ/V2N). `tutorials/sample_save_torch_model.py` shows the expected export flow.

We will close this issue soon.
